<template>
  <div>
    <ol-map>
      <ol-marker></ol-marker>
    </ol-map>
    <pre>
      &lt;template&gt;
        &lt;ol-map&gt;
          &lt;ol-marker&gt;&lt;/ol-marker&gt;
        &lt;/ol-map&gt;
      &lt;/template&gt;
    </pre>
  </div>
</template>
<style></style>
<script>
module.exports = {
  name:"MarkerExample"
};
</script>
